chore: Add nix dev env
The SDK appears to be unpacked correctly, but libsyslog-sys fails to build.
One potential problem is that it is not using glib from the SDK:

error: failed to run custom build command for `libsyslog-sys v0.1.0`

Caused by:
  process didn't exit successfully: `/home/aplj/github/apljungquist/acap-rs/target/debug/build/libsyslog-sys-99cb2a5fe133fde8/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  /nix/store/gi4cz4ir3zlwhf1azqfgxqdnczfrwsr7-glibc-2.40-66-dev/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found

  thread 'main' panicked at /home/aplj/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libsyslog-sys-0.1.0/build.rs:23:10:
  Unable to generate bindings: ClangDiagnostic("/nix/store/gi4cz4ir3zlwhf1azqfgxqdnczfrwsr7-glibc-2.40-66-dev/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace